### ISSUE TITLE
Is it possible to output file format that can be used by FlowDroid to enable ICC data-flow analysis

### ISSUE THREAD

**Issue by RichardHoOoOo** [hanada31/ICCBot#16]
Hi, I am using ICCBot to create an ATG model and I hope the model can be used by FlowDroid to enable ICC data tracking. As you may know, FlowDroid takes the result of IC3 as input to identify call sites (e.g., `startActivity`) that lead to component transitions. So the information that FlowDroid needs includes:
1. the unit that contains the call site
2. the method that the unit belongs to
3. the position of the unit in that method (i.e., the Nth unit in the method body)

According the result in `CTG.xml`, it seems ICCBot only outputs the 2nd information. I am wondering is it possible to also output the 1st and 3rd information? Thanks in advance!

**Comment by hanada31** [comment]
Thanks for using ICCBot.
We have put it into the todo list and will look at this suggestion later :-)

**Comment by hanada31** [comment]
> Hi, I am using ICCBot to create an ATG model and I hope the model can be used by FlowDroid to enable ICC data tracking. As you may know, FlowDroid takes the result of IC3 as input to identify call sites (e.g., `startActivity`) that lead to component transitions. So the information that FlowDroid needs includes:
> 
> 1. the unit that contains the call site
> 2. the method that the unit belongs to
> 3. the position of the unit in that method (i.e., the Nth unit in the method body)
> 
> According the result in `CTG.xml`, it seems ICCBot only outputs the 2nd information. I am wondering is it possible to also output the 1st and 3rd information? Thanks in advance!

The unit and the position information are added in both the CTG.xml and ICCBotResult.xml, in which the latter contains more detailed information about both the sent-out ICC and the received ICC. 
Please contact us if you need further information. Also, we'd like to know if could current version be integrated.

**Comment by RichardHoOoOo** [comment]
Hi @hanada31 , thanks for your prompt fix! I guess one thing I want to note is that FlowDroid may use an Jimple body that is slightly different from the one used by ICCBot. It is because ICC linking is an early stage in FlowDroid's analysis (even before the call graph construction). At this early stage, the Jimple body of a method is not optimized. So if ICCBot counts the unit position based on optimized Jimple bodies, it is possible that the position of a unit that launches ICC actually points to another unit when applied on the Jimple body used by FlowDroid. In my experience, setting`CodeEliminationMode` as `NoCodeElimination` can resolve the problem since it basically disables optimizations. Meanwhile, I guess different FlowDroid and Soot versions may also cause this problem. So may I ask what versions are you using? Thanks in advance!

**Comment by LightningRS** [comment]
Hi @RichardHoOoOo,

Thanks for your suggestion! We are currently working on analyzing the potential impact of Jimple body optimization.

In ICCBot 1.0 stable version, the versions of dependencies we used are listed below:

+ FlowDroid: [`soot-infoflow 2.8`](https://mvnrepository.com/artifact/de.tud.sse/soot-infoflow/2.8) and [`soot-infoflow-android 2.8`](https://mvnrepository.com/artifact/de.tud.sse/soot-infoflow-android/2.8), with some modification to enhance the callback analysis, mainly on method `runInfoflow_dummy()` and `processEntryPoint_dummy()` in SetupApplication. The `jar` files of modified versions are stored in `lib` folder under our repo root, with name [`soot-infoflow-dummy.jar`](https://github.com/hanada31/ICCBot/blob/v1.0-stable/lib/soot-infoflow-dummy.jar) and [`sootandroid-1.0-SNAPSHOT-all.jar`](https://github.com/hanada31/ICCBot/blob/v1.0-stable/lib/sootandroid-1.0-SNAPSHOT-all.jar).

+ Soot: version [`4.3.0-20220321.125138-265`](https://github.com/soot-oss/soot/commit/4abf7bccb104a7df0278704f57effd06dfbd7fde).

Since ICCBot 1.1, we **bumped the version of soot and FlowDroid**. The versions of dependencies we used are listed below:

+ FlowDroid: [`soot-infoflow 2.10.0`](https://mvnrepository.com/artifact/de.fraunhofer.sit.sse.flowdroid/soot-infoflow/2.10.0) and [`soot-infoflow-android 2.10.0`](https://mvnrepository.com/artifact/de.fraunhofer.sit.sse.flowdroid/soot-infoflow-android/2.10.0) published on maven central repository. We put the modification of callback analysis to a wrapper class named [`MySetupApplication`](https://github.com/hanada31/ICCBot/commit/bf94e07f58e1bc6b7760d46022d17cde6bb2bd22).

+ Soot: version [`4.4.0-SNAPSHOT-ICCBot`](https://github.com/LightningRS/soot-dev-iccbot), which is forked from [the latest version on develop branch of original repository](https://github.com/soot-oss/soot/commit/8d4a316c25209a7ad968ea4044fc300ac2a9faac) and fixed a ConcurrentModification bug. This is an ugly fix so that we didn't open PR to upstream.

**Comment by RichardHoOoOo** [comment]
@Hi @LightningRS , thanks for your reply! I think the versions are pretty up-to-date! Thanks for your tool!

**Comment by RichardHoOoOo** [comment]
Hi @hanada31 I would like to report one issue. When I analyzed this [app](https://github.com/woheller69/weather),

**Comment by RichardHoOoOo** [comment]
Hi @hanada31 , I would like to report one issue. When I analyzed this [app](https://github.com/woheller69/weather), I found one icc link is not reported in CTG.xml. In ICCBotResult.xml, I could find the link but it seems the unit id is not included.

The ICC link should be a simple case, which you can find in the following link.
https://github.com/woheller69/weather/blob/d1fe14969e7f19db4264240724576fd5eee3e2c1/app/src/main/java/org/woheller69/weather/weather_api/open_weather_map/ProcessRadiusSearchRequest.java#L169-L174

**Comment by LightningRS** [comment]
Hi @RichardHoOoOo,

I just took a look into the ICC that you mentioned. The conclusion is that this ICC is False Negative, and it is not a "simple" one.

As you mentioned, the link appears in ICCBotResult.xml is shown as follow:

```xml
  <Component source="org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest">
    <intentSummary>
      <source name="org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest"/>
      <destination name="org.woheller69.weather.activities.RadiusSearchResultActivity"/>
      <method value="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String,int)&gt;"/>
      <methodtrace value="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String,int)&gt;,void processSuccessScenario(java.lang.String,int)"/>
      <nodes>
        <node method="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String,int)&gt;"/>
        <node method="ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest processSuccessScenario" type="CreateMethod" unit="$r14 = new android.content.Intent"/>
        <node method="ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest processSuccessScenario" type="SetAttribute" unit="specialinvoke $r14.&lt;android.content.Intent: void &lt;init&gt;(android.content.Context,java.lang.Class)&gt;($r8, class &quot;Lorg/woheller69/weather/activities/RadiusSearchResultActivity;&quot;)"/>
        <node method="ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest processSuccessScenario" type="SetAttribute" unit="virtualinvoke $r14.&lt;android.content.Intent: android.content.Intent setFlags(int)&gt;(268435456)"/>
        <node method="ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest processSuccessScenario" type="SendIntent2ICC" unit="virtualinvoke $r8.&lt;android.content.Context: void startActivity(android.content.Intent)&gt;($r14)"/>
      </nodes>
    </intentSummary>
  </Component>
```

The source is the class `ProcessRadiusSearchRequest`, which is not the actual one. It means that ICCBot has failed to detect the source component of this ICC.

The following steps are those we took to analyze this ICC manually.

1. This ICC is defined in the method `processSuccessScenario()` of class `ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest`, 
which is an inner class of `ProcessRadiusSearchRequest`.

2. The method `ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest.processSuccessScenario()` has been used in callback method [`onResponse`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/http/VolleyHttpRequest.java#L85) in an anonymous listener, which is a parameter when constructing object `stringRequest` with type of `StringRequest`.

3. `com.android.volley.RequestQueue.add()` method has been called with object `stringRequest` as parameter, which is an Android system library API.

In current analysis strategy, we **do not model such library functions**, so there is no way to know how this object will be used subsequently.

> According to the code semantics, the call to `add()` here initiates an http request based on the `stringRequest` object,
and invokes the callback method `onResponse()` once the request is responded to.

4. The object `stringRequest` is constructed in method `make()` of class `VolleyHttpRequest`.

5. The method `VolleyHttpRequest.make()` and the object with type `ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest` has been used in
[`OwmHttpRequestForRadiusSearch$OwmHttpRequestForResults.perform()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/weather_api/open_weather_map/OwmHttpRequestForRadiusSearch.java#L73).

6. The method `OwmHttpRequestForRadiusSearch$OwmHttpRequestForResults.perform()` has been used in
[`ProcessRadiusSearchRequest.processSuccessScenario()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/weather_api/open_weather_map/ProcessRadiusSearchRequest.java#L66-L68).

7. The method `VolleyHttpRequest.make()` and the object with type `ProcessRadiusSearchRequest` has been used in
[`OwmHttpRequestForRadiusSearch.perform()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/weather_api/open_weather_map/OwmHttpRequestForRadiusSearch.java#L33).

8. The method `OwmHttpRequestForRadiusSearch.perform()` has been used in
[`RadiusSearchActivity.handleOnButtonSearchClick()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/activities/RadiusSearchActivity.java#L285-L286)

9. The method `RadiusSearchActivity.handleOnButtonSearchClick()` has been used in anonymous button on click listener callback method
[`onClick()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/activities/RadiusSearchActivity.java#L247).

10. The listener of the button `btnSearch` has been registered in
[`RadiusSearchActivity.initialize()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/activities/RadiusSearchActivity.java#L244-L251),
which has been invoked in
[`RadiusSearchActivity.onCreate()`](https://github.com/woheller69/weather/blob/e4ac2050e7a8a86d9775f2b4ab749d9f3a26fa5e/app/src/main/java/org/woheller69/weather/activities/RadiusSearchActivity.java#L91).

At this point, we got an ICC link: `org.woheller69.weather.activities.RadiusSearchActivity --> org.woheller69.weather.activities.RadiusSearchResultActivity`.

We think the key reason that cause this FN ICC link is the one shows in step 3.

**Comment by RichardHoOoOo** [comment]
Hi @LightningRS thanks for your careful explanation! One suggestion I hope to mention is that it may not be necessary for locating the source activity (i.e., `RadiusSearchActivity` in this case) since this information is not needed for FlowDroid to link components. From my testing on FlowDroid, I can conclude that it only requires the unit, its unit ID, its method, and its declaring class to connect components. Therefore, what I usually do is to create a fake activity that pretends to be the source and FlowDroid has no problem on it. Could you take this suggestion into consideration? Although the ICC link cannot be built (thus a FN), the output is still good enough to be used by FlowDroid

**Comment by hanada31** [comment]
Hi, @RichardHoOoOo Thanks for your advice! In the latest update, we have added the non-component edges in the output files.

For this example, we have:
_In CTG.xml_
```xml
  <source name="org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest" type="NotComponentSource">
    <destination ICCType="explicit" name="org.woheller69.weather.activities.RadiusSearchResultActivity" edgeType="Class2Any" method="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String)&gt;" instructionId="56" unit="virtualinvoke $r8.&lt;android.content.Context: void startActivity(android.content.Intent)&gt;($r14)" extras="ParcelableArrayList-resultList" flags="FLAG_ACTIVITY_NEW_TASK "/>
  </source>
```
_In ICCBotResult.xml_
```xml
<Component source="org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest">
    <intentSummary>
      <source name="org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest"/>
      <destination name="org.woheller69.weather.activities.RadiusSearchResultActivity"/>
      <sendICCInfo extras="ParcelableArrayList-resultList" flags="FLAG_ACTIVITY_NEW_TASK ">
        <info unit="virtualinvoke $r8.&lt;android.content.Context: void startActivity(android.content.Intent)&gt;($r14)" methodSig="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String)&gt;" instructionId="56"/>
      </sendICCInfo>
      <method value="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String)&gt;"/>
      <methodtrace value="&lt;org.woheller69.weather.weather_api.open_weather_map.ProcessRadiusSearchRequest$ProcessRadiusSearchResultRequest: void processSuccessScenario(java.lang.String)&gt;,void processSuccessScenario(java.lang.String)"/>
    </intentSummary>
  </Component>
```

**Comment by limerick1718** [comment]
I would like to express my appreciation for this wonderful tool. But I would like to ask whether you guys have implemented the function that outputs file format which can be used by FlowDroid to enable ICC data-flow analysis? 
If so, would you please kindly let me know which output file can be used?
Thank you very much and have a great day!

**Comment by hanada31** [comment]
@limerick1718 In the latest version, the output file "CTG.xml" can provide the necessary information required by Flowdroid.
Maybe you can parse that file to construct the [IccLink](https://github.com/secure-software-engineering/FlowDroid/blob/b8277a6411867b2b2d7467e784ab9d02438ab3e2/soot-infoflow-android/src/soot/jimple/infoflow/android/iccta/IccLink.java) objects and replace the original IC3Provider in FlowDroid.

**Comment by limerick1718** [comment]
> 

Thank you very much for your quick reply!
I try to implement one, but I find there is no Exit_kind in "CTG.xml" file.
`                    String ICCType = attributes.getNamedItem("ICCType").getNodeValue();
                    if (ICCType == "implicit") {
                        String action = attributes.getNamedItem("action").getNodeValue();
                        if (null == action) {
                            continue;
                        }
                        String method = attributes.getNamedItem("method").getNodeValue();
                        SootMethod fromSM = Scene.v().grabMethod(method);
                        int instructionId = new Integer(attributes.getNamedItem("instructionId").getNodeValue());
                        Stmt fromU = linkWithTarget(fromSM, instructionId);
                        String targetName = attributes.getNamedItem("name").getNodeValue();
                        IccLink iccLink = new IccLink(fromSM, fromU, Scene.v().getSootClassUnsafe(targetName));
                        //iccLink.setExit_kind(targetComp.getKind().name()); I am not sure about this
                        iccLinks.add(iccLink);
                    } `
Would you please kindly let me know where to find the "Exit_kind" value, and would you please kindly help me to check if is there any wrong mapping in my code?

**Comment by limerick1718** [comment]
Thank you very much for the help! I observe the newly added field in the CTG.xml :)
Thanks again and have a great day!
